export const LOCAL_STORAGE_KEY = {
  LENS_ACCESS_TOKEN: "lensAccessToken",
  LENS_REFRESH_TOKEN: "lensRefreshToken",
}

export const IPFS_INFURA_ID = process.env.REACT_APP_IPFS_INFURA_ID
export const IPFS_INFURA_SECRET = process.env.REACT_APP_IPFS_INFURA_SECRET

export const CONTRACT_ADDRESSES = {
  LENS_PERIPHERY: "0xD5037d72877808cdE7F669563e9389930AF404E8",
}
